### ISSUE TITLE
Color bar values

### ISSUE THREAD

**Issue by bearlyonline** [bearlyonline/hw2clim680#1]
I wasn't sure what value ranges were the best for my data, so I chose the ones that I thought fit the best. However, I am not 100% sure.

**Comment by luisortizuriarte** [comment]
They look fine, since you seem to be looking at specific dust AOD ,which is notable. You may want to make all values where AOD == 0 be white/have no color. You can mess around with the colorbar, or you can use a mask with xarray.where as we've done in class.

**Comment by bearlyonline** [comment]
I can update the assignment if you would like, but when I set it so AOT == 0 would be white, the map doesn't change. There will always be some AOT throughout the map. Even really small values that approach 0, I think it is appropriate to show that there is some Dust Extinction Aerosol Optical Thickness (AOT) across the world, even if minuscule.

The areas that have noticeably higher AOT values in comparison with those much lower valued areas are what I believe to be important to note from the plots.

**Comment by luisortizuriarte** [comment]
Rather than zero, you can choose an appropriately small small value to mask out. If there's no such small value, then you can leave as is.

**Comment by bearlyonline** [comment]
Based on what I have seen, there wouldn't be an appropriate small value to mask out data. I think it would be best to leave as is.

**Comment by luisortizuriarte** [comment]
All righty. Closing the issue and regrading. Thanks for looking into this.

**Comment by luisortizuriarte** [comment]
Actually, I can't close the issue because you created it!
